### ISSUE TITLE
ERROR AdsError: Wrong signature

### ISSUE THREAD

**Issue by TimeRider07** [adshares/ads-browser-wallet#67]
I wiped out my old computer that I was using ADS wallet and transferred it to my new computer.

But while trying to send ADS, I get the ERROR
AdsError: Wrong signature

Can someone help me on it? What can I do?

**Comment by m-pilarczyk** [comment]
Make sure you are not using testnet, then go to Settings -> Manage Keys and make sure your keys are there (match the public key to your account in blockexplorer). If not, try importing keys or the seed pharse.
