### ISSUE TITLE
funds not rec

### ISSUE THREAD

**Issue by perryone** [adshares/ads-browser-wallet#87]
hello, i have transfered ADS to my metamask wallet and i didnt rec it yet...  pls check and advice.

{ 
  "size": 125,
  "node": 48,
  "target_address": "0001-00000003-AB0C",
  "message": "000000575241505F4253433A1894543AB3E878FEDD0485BA6E0D1CEF01B6E972",
  "sender_address": "0030-00000080-AC58",
  "user": 128,
  "block_id": "627BD400",
  "time": "2022-05-11T15:24:52+00:00",
  "target_node": 1,
  "message_id": "0030:000002C2",
  "amount": "95400000000000",
  "node_id": "0030",
  "signature": "694ED37EDBC5859E5EA1B5DDD6529B24B254B224D35CB0962FF35B8D33C9F1010FA3CC5A31A91ABD96E6B46593AC998B08B48760191DE77AF781784BA80EC108",
  "target_user": 3,
  "msg_id": "9",
  "type": "send_one",
  "id": "0030:000002C2:0001",
  "sender_fee": 95400000000
}

**Comment by m-pilarczyk** [comment]
Here you can find transaction's details: https://bscscan.com/tx/0xcae67f49000f02f2e37d8ea12546a5c8a2404d0c50b531ec2a16b0ffc249de50
